### ISSUE TITLE
Broken UI in version 4.0.2

### ISSUE THREAD

**Issue by MuhammadRazaAslam** [sidekiq-scheduler/sidekiq-scheduler#393] opened 2022-07-21 12:55 UTC
Hi,

I upgraded from version `3.0.2` to `4.0.2`. Now, Recurring Job page UI is broken in the `4.0.2` version. 

<img width="1792" alt="Screenshot 2022-07-21 at 5 50 44 PM" src="https://user-images.githubusercontent.com/19810462/180217868-5f1325aa-bcd5-4adb-9d5e-fa0499a0a05e.png">

**Comment by marcelolx** [comment] 2022-07-21 13:26
which version of sidekiq are you using?

**Comment by marcelolx** [comment] 2022-07-21 13:27
also, are you using webpacker, sprockets? It would be ideal if you could provide a sample app so we can reproduce your problem

We had a recent issue related to this https://github.com/sidekiq-scheduler/sidekiq-scheduler/issues/364 but it should be fixed

**Comment by MuhammadRazaAslam** [comment] 2022-07-21 13:51
@marcelolx My sidekiq version **6.1.3**.

**Comment by marcelolx** [comment] 2022-07-21 15:59
Can you please provide a sample app? My local sample app with sidekiq 6 + sidekiq-scheduler 4.0.2 I don't get this error

**Comment by houdl** [comment] 2022-07-23 05:31
@MuhammadRazaAslam  @marcelolx 
this pull request may solve this bug
https://github.com/sidekiq-scheduler/sidekiq-scheduler/pull/394

**Comment by marcelolx** [comment] 2022-07-23 09:36
Thanks @houdl! PR merged, can you point you gemfile to the master branch and see if it is fixed @MuhammadRazaAslam?

**Closed** 2022-07-23 09:43 UTC

**Comment by houdl** [comment] 2022-07-23 09:59
@marcelolx   it was merged branch  v3-stable , you may need check pick it to master.

**Comment by houdl** [comment] 2022-07-23 10:09
@marcelolx   pull request for master  https://github.com/sidekiq-scheduler/sidekiq-scheduler/pull/395

**Comment by marcelolx** [comment] 2022-07-23 10:37
oh 🤦‍♂️ PR merged!

**Comment by MuhammadRazaAslam** [comment] 2022-12-27 09:33
@marcelolx @houdl I have tested it again so it's not fixed yet.

**Comment by marcelolx** [comment] 2022-12-27 13:13
@MuhammadRazaAslam please come up with a sample app simulating your problem, we can't keep trying to guess what is not fixed... Here was someone else that in theory the CSS was broken too and turns out it wasn't https://github.com/sidekiq-scheduler/sidekiq-scheduler/issues/415, so if you come up with a sample app that reproduces your problem we can help, and fix if anything is really broken in the gem, otherwise it is likely that is some config of your application.

**Comment by MuhammadRazaAslam** [comment] 2022-12-28 10:55
@marcelolx Sample App Link: https://github.com/MuhammadRaza29/sidekiq-scheduler-integration

**Comment by houdl** [comment] 2022-12-28 12:13
@MuhammadRazaAslam  you can reinstall  sidekiq-scheduler version: 4.0.3, may solve your problem.

i pull your sample app code, bundle install , and could not found 404. 

you can check recurring_jobs.css in local.

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/8501458/209810486-130d3d41-0f08-4f68-b927-9e7c2470cacf.png">
<img width="993" alt="image" src="https://user-images.githubusercontent.com/8501458/209810521-872134a2-af8d-42f7-b07b-b4bf6e6453a3.png">

**Comment by marcelolx** [comment] 2022-12-28 12:44
@MuhammadRazaAslam I did clone your sample app locally and did the following steps, the UI is not broken as can be seen in the screenshot below (same results as the ones shown by @houdl)

1. `git clone https://github.com/MuhammadRaza29/sidekiq-scheduler-integration.git`
2. `cd sidekiq-scheduler-integration`
3. `bundle install`
4. `bin/rails db:setup`
5. `bin/rails s`
6. `bundle exec sidekiq`
7. Opened the following URL `http://localhost:3000/sidekiq` 
8. And then did go to the "Recurring Jobs" tab

![image](https://user-images.githubusercontent.com/20196775/209813422-ce79470a-0ef0-4073-b6f5-262617011905.png)

I did even install the v5 beta version and got the same results.
```ruby
gem 'sidekiq-scheduler', "5.0.0.beta1"
```

@MuhammadRazaAslam If you check your application `Gemfile.lock` which version is installed for the `rack` gem? The sample app version is `rack (2.2.5)` but your application version could be lower and the UI is broken in your app because of that? Similar to the problem mentioned [here](https://github.com/sidekiq-scheduler/sidekiq-scheduler/issues/415#issuecomment-1360078453)?

**Comment by MuhammadRaza29** [comment] 2022-12-28 16:08
@marcelolx @houdl UI is also broken in your screenshots.

It should be
https://raw.githubusercontent.com/sidekiq-scheduler/sidekiq-scheduler/master/images/recurring-jobs-ui-tab.png

**Comment by marcelolx** [comment] 2022-12-28 16:22
@MuhammadRaza29 what is exactly broken? The table? We removed the table here https://github.com/sidekiq-scheduler/sidekiq-scheduler/pull/344

**Comment by marcelolx** [comment] 2022-12-28 16:23
> Table columns and borders are missing.

They are not missing, we removed the table intentionally.

**Comment by MuhammadRaza29** [comment] 2022-12-28 16:35
@marcelolx Ohh got it but table looks great and it's readable. I think table should be added again.

**Comment by marcelolx** [comment] 2022-12-28 16:53
@MuhammadRaza29 That won't happen.
